comentando husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,7 @@
-echo 'Check for linting errors and run run prettier...'
+#echo 'Check for linting errors and run run prettier...'
 
-(npm run lint && npm run format) || (
-  echo 'Linting errors failed. Please fix them before commiting.' && exit 1
-)
+#(npm run lint && npm run format) || (
+  #echo 'Linting errors failed. Please fix them before commiting.' && exit 1
+#)
 
-echo 'Done'
+#echo 'Done'
